### ISSUE TITLE
After delete Node in Tree i get Uncaught Error: Syntax error, unrecognized expression: #

### ISSUE THREAD

**Issue by allipierre** [vakata/jstree#1828]
Hey,
after delete Node in Tree than refresh, i get that Error
Uncaught Error: Syntax error, unrecognized expression: #

The Delete works fine but refresh get me that error

jquery-2.1.3.min.js?v=5.0.3.00.03:2 Uncaught Error: Syntax error, unrecognized expression: #
    at Function.gb.error (/i/libraries/jquery/2.1.3/jquery-2.1.3.min.js?v=5.0.3.00.03:2:12467)
    at gb.tokenize (i/libraries/jquery/2.1.3/jquery-2.1.3.min.js?v=5.0.3.00.03:2:18394)
    at Function.gb [as find] (/i/libraries/jquery/2.1.3/jquery-2.1.3.min.js?v=5.0.3.00.03:2:6816)
    at n.fn.init.find (/i/libraries/jquery/2.1.3/jquery-2.1.3.min.js?v=5.0.3.00.03:2:23396)
    at n.fn.init (/i/libraries/jquery/2.1.3/jquery-2.1.3.min.js?v=5.0.3.00.03:2:23940)
    at n (/i/libraries/jquery/2.1.3/jquery-2.1.3.min.js?v=5.0.3.00.03:2:405)
    at Object._get_node (/r/109/files/plugin/57790749189928318421/v34/jquery.jstree.pre1.8.js:1094:16)
    at Object.$.jstree._fn.(anonymous function) [as _get_node] (r/109/files/plugin/57790749189928318421/v34/jquery.jstree.pre1.8.js:227:19)
    at Object.open_node (/r/109/files/plugin/57790749189928318421/v34/jquery.jstree.pre1.8.js:649:16)
    at Object.$.jstree._fn.(anonymous function) [as open_node] (/files/plugin/57790749189928318421/v34/jquery.jstree.pre1.8.js:234:19)
gb.error @ jquery-2.1.3.min.js?v=5.0.3.00.03:2
gb.tokenize @ jquery-2.1.3.min.js?v=5.0.3.00.03:2
gb @ jquery-2.1.3.min.js?v=5.0.3.00.03:2
find @ jquery-2.1.3.min.js?v=5.0.3.00.03:2
n.fn.init @ jquery-2.1.3.min.js?v=5.0.3.00.03:2
n @ jquery-2.1.3.min.js?v=5.0.3.00.03:2
_get_node @ jquery.jstree.pre1.8.js:1094
$.jstree._fn.(anonymous function) @ jquery.jstree.pre1.8.js:227
open_node @ jquery.jstree.pre1.8.js:649
$.jstree._fn.(anonymous function) @ jquery.jstree.pre1.8.js:234
(anonymous) @ jquery.jstree.pre1.8.js:523
each @ jquery-2.1.3.min.js?v=5.0.3.00.03:2
reload_nodes @ jquery.jstree.pre1.8.js:522
$.jstree._fn.(anonymous function) @ jquery.jstree.pre1.8.js:234
(anonymous) @ jquery.jstree.pre1.8.js:426
(anonymous) @ jquery.jstree.pre1.8.js:1671
load_node_json @ jquery.jstree.pre1.8.js:1742
$.jstree._fn.(anonymous function) @ jquery.jstree.pre1.8.js:234
load_node @ jquery.jstree.pre1.8.js:1671
$.jstree._fn.(anonymous function) @ jquery.jstree.pre1.8.js:234
$.jstree._fn.(anonymous function) @ jquery.jstree.pre1.8.js:234
init @ jquery.jstree.pre1.8.js:426
$.jstree._fn.(anonymous function) @ jquery.jstree.pre1.8.js:234
(anonymous) @ jquery.jstree.pre1.8.js:162
contextmenu.js:8 

How can i handle it?
Thanks

**Comment by vakata** [comment]
As far as I understand this code uses jsTree v.1 which has not been supported for years. I am afraid I can not help - if this is a recent version - let me know and I will reopen.
